name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  ACTION:
    description: "Who to greet"
    required: true
    default: "echo 'hi'"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "cloud-lightning"
  color: "purple"
